import streamlit as stimport google.generativeai as genaifrom gtts import gTTSimport io
# Page Configuration# Page Configuration
# Page Configurationst.write("Video Editor များနှင့် လူငယ် Creator များအတွက် အဆင့် မင့် AI Voice & Chat Assistant")
# Free Credit System Initializationif 'used_credits' not in st.session_state:    st.session_state.used_credits = 0
DAILY_LIMIT = 3000remaining_credits = DAILY_LIMIT - st.session_state.used_credits# Sidebar Setup# Sidebar Setupapi_key = st.sidebar.text_input("Google AI Studio API Key", type="password")
api_key = st.sidebar.text_input("Google AI Studio API Key", type="password")
# Multi-Language Voice Option Databaselanguages_db = {    " မန်မာ (Burmese)": {"code": "my", "voices": ["Standard Female"]},    "English (US)": {"code": "en", "voices": ["Male Accent", "Female Accent"]},    "ไทย (Thai)": {"code": "th", "voices": ["Standard Thai"]},    "日本語 (Japanese)": {"code": "ja", "voices": ["Tokyo Native"]}}
# Tabs Layout# Tabs Layout
with tab1:    st.header("စာသားမှ အသ ပြောင်းလဲ ခြင်း")    col1, col2 = st.columns(2)    with col1:        lang_choice = st.selectbox("ဘာသာစကား ရေွးခြျယ်ရေန်", list(languages_db.keys()))        voice_choice = st.selectbox("အသအမျိုးအစား", languages_db[lang_choice]["voices"])    with col2:        speed_choice = st.slider("အသနှုန်း (Speed)", 0.5, 2.0, 1.0, 0.1)
    text_input = st.text_area("အသ ပြောင်းမည့် စာသားများကိုံ ရိုံက်ထည့်ပြေါ")
    text_input = st.text_area("အသ ပြောင်းမည့် စာသားများကိုံ ရိုံက်ထည့်ပြေါ")        if not text_input:            st.error("ကျးဇူး ပြေု၍ စာသားတစ်ခြုံခြုံ ရိုံက်ထည့်ပြေးပြေါ။")        elif len(text_input) > remaining_credits:            st.error("⚠️ သင်၏ ယန ့အတွက် Free Credit မလုံလာက်တာ့ပြေါ။")        else:            with st.spinner("အသဖိုံင် ဖန်တီးနပြေါသည်..."):                try:                    lang_code = languages_db[lang_choice]["code"]                    tts = gTTS(text=text_input, lang=lang_code, slow=(speed_choice < 1.0))                    fp = io.BytesIO()                    tts.write_to_fp(fp)                    fp.seek(0)                    st.audio(fp, format='audio/mp3')                    st.audio(fp, format='audio/mp3')                    st.session_state.used_credits += len(text_input)                except Exception as e:                    st.error(f"Error: {e}")
with tab2:    st.header("AI Creator Chat")    if not api_key:    if not api_key:    else:        genai.configure(api_key=api_key)        model = genai.GenerativeModel('gemini-1.5-flash')        chat_input = st.text_input("AI အား စိတ် ကိုက်မး မန်းရေန်")        if st.button("Ask AI ✨"):            with st.spinner("AI စဉ်းစားနပြေါသည်..."):                try:                    response = model.generate_content(chat_input)                    response = model.generate_content(chat_input)                    st.write(response.text)                except Exception as e:                    st.error(f"Error: {e}")
else:
                st.error("မေးခွန်းတစ်ခုခု ရိုက်ထည့်ပေးပါဦးဗျာ။")
